// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZO8Ivb34_xZMDAk7g9Ziwyif5qeQZrc',
    appId: '1:223854375561:web:a4616200030942b65f8c58',
    messagingSenderId: '223854375561',
    projectId: 'fir-test-532fb',
    authDomain: 'fir-test-532fb.firebaseapp.com',
    storageBucket: 'fir-test-532fb.appspot.com',
    measurementId: 'G-6B3X5DER4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFs1SWAEeaF6d1TPnwARRPiXEwfryWonk',
    appId: '1:223854375561:android:a993e741cf60e1165f8c58',
    messagingSenderId: '223854375561',
    projectId: 'fir-test-532fb',
    storageBucket: 'fir-test-532fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQ0QsMQozTWc6bwUPRh0khSLBO_bBVmY',
    appId: '1:223854375561:ios:77564bb9f511a47b5f8c58',
    messagingSenderId: '223854375561',
    projectId: 'fir-test-532fb',
    storageBucket: 'fir-test-532fb.appspot.com',
    androidClientId: '223854375561-dqn1g9hi06aba0du1e5ordv57hl53hae.apps.googleusercontent.com',
    iosClientId: '223854375561-tnvvn863a587ovmmt308dsdcibpdbfil.apps.googleusercontent.com',
    iosBundleId: 'com.survivalcoding.vertexaisample.vertexaiSample',
  );
}
